#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap us &
picom
feh --bg-scale ~/wallpapers/arch.png
/home/modo/.config/polybar/launch.sh

bspc monitor DP-3 -d I II III IV V 
bspc monitor HDMI-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

